### ISSUE TITLE
Need some instructions to implement it in the existing ERP program.

### ISSUE THREAD

**Issue by IMPranshu** [Mittal-Analytics/gst-e-invoicing#2]
Some instructions on how to use the current code will be helpful in implementing it in old ERP software for businesses.

**Comment by pratyushmittal** [comment]
Hey @IMPranshu, yeah we are working on the docs and integrations. We will add them soon.

Currently the library provides the building blocks for authentication and IRN generation. The working examples can be seen in tests: https://github.com/Mittal-Analytics/gst-e-invoicing/blob/main/tests/test.py

We will try to add production endpoints and better examples over next few days.

**Comment by pratyushmittal** [comment]
Created basic docs at: https://github.com/Mittal-Analytics/gst-e-invoicing/blob/main/docs/index.md

Will soon try to generate a website for the above using MkDocs.

**Comment by pratyushmittal** [comment]
Added automatic generation of docs using MkDocs.

The docs are now available at: https://mittal-analytics.github.io/gst-e-invoicing/
