### ISSUE TITLE
Usage of your application

### ISSUE THREAD

**Issue by JalanStudio** [Mittal-Analytics/gst-e-invoicing#7]
### Introduction
Greetings, I am **Jalan**(_obviously not my real name as I prefer to not use it online_), a fellow developer from India. I have been assigned to make a application **similar** to yours and lets just say this project would be a **huge help** to me due to my **situation**(_which I will talk about in a minute_)

### My goal
I would like to take your application and **modify** it to my client's needs, if you allow that is. Obviously I will be providing credit in my application inside the credits section and a link to this Github repository

### What is my situation here?
I had developed a program similar to this over a span of **2 months**(_since I am unfamilar with the Government APIs and others_) but unfortunately lost it due to **corrupted hard drive** and my client requires it in a month

### So, what now?
As I mentioned before, I would like to modify your application to meet my client's needs. Unfortunately, credit is the only thing I will be able to provide you since even my profit margin is low

### Conclusion
I request you to allow me to modify your application and make money off of it(_a one time payment with a low profit margin that is_), thank you for your time. Have a great day ahead

**Comment by pratyushmittal** [comment]
Hi Jalan, the library is published under the GPL-3.0 license. You can see the license here https://github.com/Mittal-Analytics/gst-e-invoicing/blob/main/LICENSE

The GPL 3 license allows you to modify the code as well as use it for commercial purposes. The only restriction is, you should publish the modifications and enhancements under the same GPL 3 license.

Basically, you need to open-source the modifications you make for your clients and publish them in the new fork.

Hope this helps.

**Comment by JalanStudio** [comment]
Pardon me but is it necessary? As my client is a quite a decent company and would really like it if it is not open source(_since they paid for it and all that_)
